### ISSUE TITLE
Possible Value Error processing POST request with an empty body.

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Rumba#11]
5:VALUE ERROR
GetFormValue[4] c←⍺.ProcessedContent
                 ∧

⍺.ProcessedContent does not exist in the namespace.

**Comment by PaulMansour** [comment]
Fixed a while ago.

**Comment by PaulMansour** [comment]
Nope, not fixed a while ago, fixed now.

**Comment by PaulMansour** [comment]
Fixed now!
