### ISSUE TITLE
INDEX ERROR in GatherResponseMessage on "Messages"

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Rumba#15]
To reproduce the bug run this function@

```
∇ ns←test;stop;ns;R;client;request;response
    stop←{⍺←200 ⋄ ⍺=⍵: ⋄ ⎕←⍵ ⋄ ∘∘∘}
    ns←⎕NS''
    R←#.CarlisleGroup.Rumba
    {}R.Core.InitConga''
    R.Conga.X509Cert.LDRC←R.DRC
    client←R.Core.NewClient 0
    client.Port←443
    client.Secure←1
    client.X509←⎕NEW R.Conga.X509Cert
    client.Host←'api.github.com'
    request←R.Core.NewRequest 0
    request.URI←'https://api.github.com/repos/aplteam/Meddy/releases/latest'
    {}client R.Core.Send request
    response←client R.Core.Receive 0
    {}client R.Core.Close 0
    stop response.StatusCode
∇  ⍝Done
```

Executing this results in

```
INDEX ERROR
GatherResponseMessage[13] n←(1+c.Messages⍳⍵)⊃c.Messages
```

**Comment by norberturkiewicz** [comment]
Rumba does not properly check the actual content body size for Content-Length IF the Content-Length header is omitted in the result from the server.  Should be updated to read content until socket is closed by server.

@aplteam you can temporarily work around the issue by providing a User-Agent header in your request, which will provide your desired content.

**Comment by aplteam** [comment]
> ...ntil socket is closed by server.

What if the connection is a permanent one?!

**Comment by PaulMansour** [comment]
Do we know if it is possible for the server to send back pipelined messages, unchunked, without content-length?. Or rather is it possible for the client to know where one message ends and the next one begins?

**Comment by PaulMansour** [comment]
Fixed. Going, for now, with the assumption that if no content-length header in response, that we must go with server closing connection as end-of-content.
