### ISSUE TITLE
Invalid function call in Core.LogHTTPToSession

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Rumba#33]
`Core.LogHTTPToSession` contains this line:

```
ts←#.CarlisleGroup.Rumba.Core.GetCurrentUTCHttpDate''
```

**Comment by norberturkiewicz** [comment]
@aplteam that line has been changed to

ts←GetCurrentUTCHttpDate''

on Feb. 22.  5da91055c31dd43660ed36756c4ecb33c052075c


Are you on the latest pull?

**Comment by aplteam** [comment]
No, just the latest release.

**Comment by aplteam** [comment]
Actually I am since that has the same meaning right now

**Comment by norberturkiewicz** [comment]
Is this not the function you have?

```apl
 LogHTTPToSession←{
    ⍝ ⍺ ←→ Server
    ⍝ ⍵ ←→ Response
     ~⍺.LogHTTPToSession:0
     m←⍵.Message
     ts←GetCurrentUTCHttpDate''
     ⎕←ts,': ',m.Connection.PeerAddress,' ',⍕⍺.Port':'⍵.StatusCode m.Method m.RequestTarget
     0
 }
```

I downloaded 1.9 and copied from the source zip file

**Comment by aplteam** [comment]
Sorry, found it. I've compared 0.1.6 with 0.1.9 but the latest version of the comparison utility has changed the rules regarding what pops up in the left and right window: now the cursor position rules the day. Bah!

As a consequence I compared 0.1.9 with 0.1.6 rather the other way around.

Case closed.
