### ISSUE TITLE
UpdateStats counts HEAD requests as GET requests

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Rumba#43]
And one could also argue that `Method` is wrong

**Comment by PaulMansour** [comment]
Fixed a while back I think.

**Comment by PaulMansour** [comment]
> And one could also argue that Method is wrong

Not sure what this means.

**Comment by aplteam** [comment]
Hmmm. Sorry, I have no idea what I tried to say back then...

**Comment by PaulMansour** [comment]
My fault for letting it go that long!
