### ISSUE TITLE
Suggestions regarding ErrorInRumba 

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Rumba#44]
1. `⎕OFF` should use a right "argument" that is not 0, indicating an error to the calling process if there is any.
1. It should attempt to log the `⎕OFF` under strict error trapping and maybe also `⎕DMX.EM`.
1. The function should check whether a Ride session is currently connected and if so **_not_** execute `⎕OFF`, allowing the user to investigate. If somebody has connected with Ride there is a reason, possibly an interest in finding out what is causing the `⎕OFF`.

   Something like this:

```
 :If 3501⌶0                           
     TRAP←⎕TRAP  ⍝ Remember setting for inspection
     ⎕TRAP←0 'S'
     ∘∘∘                     ⍝ Check it out, dear ⎕AN
 :EndIf
```

**Comment by PaulMansour** [comment]
Would it be better to simply NOT trap the error in the ServerLoop function if there is a ride session? Then it will suspend where the error is, rather than cutting back and executing the trap. 

There error is already logged in ErrorInRumba. Do you want more logging? Or just an additional trap if the logging itself fails....

**Comment by PaulMansour** [comment]
Also,  if one were going to use:

 ∘∘∘                    

to force a stop/suspend, any reason not to use ⎕SIGNAL?

**Comment by aplteam** [comment]
> Would it be better to simply NOT trap the error in the ServerLoop function if there is a ride session? Then it will suspend where the error is, rather than cutting back and executing the trap.

That has merits, yes, but then a Rider might want to watch the behaviour of the error trapping.

> There error is already logged in ErrorInRumba. Do you want more logging? Or just an additional trap if the logging itself fails....

Yes, I withdraw this part.

Regarding `∘∘∘` versus `⎕signal`, `∘∘∘` stops on the spot, `⎕signal` leaves the current function and returns to the caller (and implicitly allowing a thread switch), that's why I preferred `∘∘∘`.

**Comment by PaulMansour** [comment]
> That has merits, yes, but then a Rider might want to watch the behaviour of the error trapping.

Ok, but which option is more useful? I would think the bug itself, stopping exactly where it occurs is more useful than behavior of error trapping, which could be done in a controlled environment.

**Comment by aplteam** [comment]
Agreed. 

My thinking was influenced by the fact that I just looked into a badly behaving `⎕TRAP`...

**Comment by PaulMansour** [comment]
Done
