### ISSUE TITLE
ProcessResponseLine crashes on invalid host responses

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Rumba#47]
When requesting the Guardian home page from https://guardian.co.uk/ Rumba crashed because the response from the server has only a length of 2, so the line 

```
     ⍵.ReasonPhrase←↑{⍺,' ',⍵}/2↓m
````
crashes.

Instead of crashing it seems to be better to check before that line is executed:

```
  2=≢m:⍵  ⍝ Host response is invalid, and there is nothing we can do about it
```

**Comment by PaulMansour** [comment]
I'm not sure its invalid. It does not have a reason phrase. I can't just guard around it, as ReasonPhrase will then be undefined. Maybe I should look up the reason phrase if none is provided.

**Comment by PaulMansour** [comment]
Just setting ReasonPhrase to empty for now.  

Fixed
