### ISSUE TITLE
Problem with PercentEncode

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Rumba#53]
This function has a problem:

```
 PercentDecode←{
     dec←{⎕ML ⎕IO←0
         ⍉16⊥16|'0123456789ABCDEF0123456789abcdef'⍳⍉↑⍵
     }
     v←'%20',⍵
     p←(v≠'%')⊂v
     p2←dec 2↑¨p
     p3←2↓¨p
     b←1↓∊0,¨'+'=p3     ⍝ For backwards compatability we attempt to decode + as ' '
     r←'UTF-8'⎕UCS 1↓⊃,/p2,¨⎕UCS¨p3
     0=+/b:r            ⍝ No blanks: done
     (b/r)←' '
     r
 }
```
I got this as data:
```
 content  +%E2%8D%B3%0D%0A    
```

`content` should be just ` ⍳`: a space followed by an iota. This causes a LENGTH ERROR.

Generally speaking, when the data carries both a space and a multi-byte character it goes wrong.

**Comment by aplteam** [comment]
There is a second problem: the LENGTH ERROR should result in Rumba returning 500, but instead the user gets a message saying that not secure connection could be established.

**Comment by PaulMansour** [comment]
OK, that's the old + versus %20 for blank thing.
