### ISSUE TITLE
PATCH always sends an empty body

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Rumba#54]

**Comment by PaulMansour** [comment]
Can you elaborate?  On the client side?

**Comment by PaulMansour** [comment]
Do you have a fix?

**Comment by aplteam** [comment]
I am afraid no. Too busy...

**Comment by PaulMansour** [comment]
Ok, I'll figure it out.

**Comment by aplteam** [comment]
The problem is that when I assign a content on the server side it's not
returned: it's always (literally) empty.

**Comment by aplteam** [comment]
The word "server" should have been "client"...

**Comment by PaulMansour** [comment]
So when the client is sending a PATCH request with content, the server does not receive the content? Correct?

**Comment by aplteam** [comment]
Exactly

**Comment by PaulMansour** [comment]
Ok, I'll write a new test and see what's up.

**Comment by PaulMansour** [comment]
Found it. Fixed.
