### ISSUE TITLE
Change suggested for WaitForData

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Rumba#55]
In `WaitForData` this line:

```
          e d←⊃⎕TGET ⍵.Tid
```

can cause a LENGTH ERROR in case Rumba is interrupted by the user but there are no threads running.

In order to avoid this I suggest this change:

```
         tids←⎕TGET ⍵.Tid
         0=⍴,tids:∇ ⍵  ⍝ Not using unmatch here due to font problems: ≢might look strange
         e d←⊃tids
```

**Comment by PaulMansour** [comment]
Done.
