### ISSUE TITLE
QTSToHTTPDate function sets the wrong timezone

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Rumba#9]
I'm in CST at 10:08 am

⎕ts
2018 4 11 10 9 10 747
      QTSToHTTPDate ⎕ts
Wed, 11 Apr 2018 10:09:12 GMT

Maybe update the function comments to state that inputs needs to be in GMT?

**Comment by norberturkiewicz** [comment]
This will most likely remain until Dyalog 18 with native cross-platform date and time library support.

**Comment by PaulMansour** [comment]
I think if you have real server, the machine time should be set to GMT.
I'm goin to close this, but feel free to re-open if you think necessary.
